-- ============================================================
-- NEW STAR — UPDATE V3 (3º arquivo)
-- Linhas de produto + Talão de Pedido Digital (Módulo B)
-- ============================================================

-- PRODUTOS -----------------------------------------------------
-- Tabela única: linha de produto + código do talão + preços das
-- duas tabelas + unidades por placa P/G. Nada disso é digitado
-- pelo vendedor — tudo vem do cadastro (editável no Admin).
create table if not exists produtos (
  id uuid primary key default gen_random_uuid(),
  codigo text not null,
  nome text not null,
  variacao text,                    -- ex.: Classic / M. Encantado / Prata / Dourado
  linha text,                       -- linha de produto (upsell + ranking)
  preco_simples numeric,            -- Tabela Simples   (null = preço a cadastrar)
  preco_lucro numeric,              -- Lucro Presumido  (null = preço a cadastrar)
  unid_placa_p int not null,        -- unidades na placa Pequena
  unid_placa_g int not null,        -- unidades na placa Grande
  ativo boolean not null default true,
  created_at timestamptz not null default now()
);

create unique index if not exists uq_produtos_codigo_variacao
  on produtos (codigo, coalesce(variacao, ''));

-- Catálogo real do talão físico. Preços não informados ficam NULL
-- (o app bloqueia o lançamento e pede cadastro no Admin — nunca inventa).
insert into produtos (codigo, nome, variacao, linha, preco_simples, preco_lucro, unid_placa_p, unid_placa_g) values
  ('4109', 'BRAG — Argolinha',                        null,           'Argolinhas',    12.60, 14.50, 48, 72),
  ('3719', 'BRAG Zircônia — Argolinha de Zircônia',   null,           'Argolinhas',    null,  null,  48, 72),
  ('4031', 'BRG — Brinco Grande',                     null,           'Brincos',       null,  null,  32, 48),
  ('4017', 'BRP — Brinco Pequeno',                    'Classic',      'Brincos',       8.99,  10.25, 64, 99),
  ('4017', 'BRP — Brinco Pequeno',                    'M. Encantado', 'Brincos',       null,  null,  64, 99),
  ('8073', 'BRP Ponto de Luz — Zircônia',             null,           'Brincos',       12.60, 14.50, 64, 99),
  ('8790', 'DIVA — Gargantilha Coleção Diva',         null,           'Gargantilhas',  null,  null,  48, 72),
  ('2927', 'FOR MEN — Gargantilha Col. For Men',      null,           'Gargantilhas',  null,  null,  64, 99),
  ('8585', 'GAR PARIS — Gargantilha Paris',           null,           'Gargantilhas',  26.50, 29.90, 16, 22),
  ('8677', 'LUXO — Brinco Argolinha',                 'Prata',        'Luxo',          25.50, 29.90, 48, 72),
  ('8677', 'LUXO — Brinco Argolinha',                 'Dourado',      'Luxo',          25.50, 29.90, 48, 72),
  ('8820', 'NEW YORK — Gargantilha Col. New York',    null,           'Gargantilhas',  30.95, 34.95, 16, 22),
  ('8806', 'PRATA 925 — Brinco Coleção Prata',        null,           'Prata 925',     null,  null,  48, 72),
  ('8899', 'PRATA 925 — Gargantilha Coleção Prata',   null,           'Prata 925',     null,  null,  16, 22),
  ('4062', 'PULA — Pulseira Adulta',                  null,           'Pulseiras',     22.10, 25.25, 16, 22),
  ('4024', 'PUL — Pulseira Infantil',                 null,           'Pulseiras',     16.50, 18.80, 16, 22),
  ('5300', 'TORNOZELEIRA',                            null,           'Tornozeleiras', null,  null,  16, 22)
on conflict (codigo, coalesce(variacao, '')) do nothing;

-- LINHAS QUE O CLIENTE TRABALHA -------------------------------
create table if not exists cliente_produtos (
  cliente_id uuid not null references clientes(id) on delete cascade,
  produto_id uuid not null references produtos(id) on delete cascade,
  adicionado_em timestamptz not null default now(),
  primary key (cliente_id, produto_id)
);

-- PEDIDOS (talão digital) -------------------------------------
create table if not exists pedidos (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity unique,
  cliente_id uuid not null references clientes(id),
  representante_id uuid not null references representantes(id),
  data date not null default current_date,
  tabela text not null check (tabela in ('simples','lucro')),
  condicao_pagamento text,
  status text not null default 'rascunho'
    check (status in ('rascunho','concluido','cancelado')),
  total_unid_colocadas int not null default 0,
  total_unid_dev_display int not null default 0,
  total_unid_dev_quebrada int not null default 0,
  total_unid_vendidas int not null default 0,
  total_valor numeric not null default 0,        -- valor efetivamente vendido
  assinatura text,                               -- PNG base64 — vínculo permanente
  assinado_em timestamptz,
  visita_id uuid,
  obs text,
  created_at timestamptz not null default now()
);

create index if not exists idx_pedidos_cliente on pedidos(cliente_id);
create index if not exists idx_pedidos_data    on pedidos(data);

create table if not exists pedido_itens (
  id uuid primary key default gen_random_uuid(),
  pedido_id uuid not null references pedidos(id) on delete cascade,
  produto_id uuid not null references produtos(id),
  tamanho text not null check (tamanho in ('P','G')),
  placas int not null default 1 check (placas > 0),
  unid_por_placa int not null,                   -- snapshot do cadastro na hora
  unid_colocadas int not null,                   -- placas × unid_por_placa
  dev_display int not null default 0,            -- devolução: subcoluna Display
  dev_quebrada int not null default 0,           -- devolução: subcoluna Quebrada
  unid_vendidas int not null,                    -- colocadas − display − quebrada
  preco_unit numeric not null,                   -- snapshot do preço da tabela usada
  valor_total numeric not null,                  -- vendidas × preço
  created_at timestamptz not null default now()
);

create index if not exists idx_itens_pedido on pedido_itens(pedido_id);

-- ============================================================
-- CONCLUSÃO DO PEDIDO → integração com o Módulo A
-- Fluxo do app: insert pedido (rascunho) → insert itens →
-- update status='concluido' (com assinatura). Este trigger então:
--   1. recalcula totais a partir dos itens
--   2. registra/atualiza a visita do dia (fez_pedido, valor vendido)
--      → a comissão 15%/10% + prazo Clamed sai do trigger de visitas
--   3. marca as linhas do pedido como "linhas que o cliente trabalha"
-- ============================================================
create or replace function fn_pedido_concluir() returns trigger as $$
declare
  v_visita_id uuid;
begin
  if new.status = 'concluido' and coalesce(old.status, '') <> 'concluido' then
    select coalesce(sum(unid_colocadas), 0),
           coalesce(sum(dev_display), 0),
           coalesce(sum(dev_quebrada), 0),
           coalesce(sum(unid_vendidas), 0),
           coalesce(sum(valor_total), 0)
      into new.total_unid_colocadas, new.total_unid_dev_display,
           new.total_unid_dev_quebrada, new.total_unid_vendidas, new.total_valor
      from pedido_itens where pedido_id = new.id;

    if new.assinado_em is null and new.assinatura is not null then
      new.assinado_em := now();
    end if;

    -- visita do dia deste cliente: atualiza se existir, senão cria
    select id into v_visita_id from visitas
     where cliente_id = new.cliente_id and data = new.data
     order by created_at desc limit 1;

    if v_visita_id is null then
      insert into visitas (cliente_id, representante_id, data, realizada, fez_pedido, pedido_id, valor_pedido)
      values (new.cliente_id, new.representante_id, new.data, true, true, new.id, new.total_valor)
      returning id into v_visita_id;
    else
      update visitas
         set realizada = true, fez_pedido = true,
             pedido_id = new.id, valor_pedido = new.total_valor,
             representante_id = coalesce(representante_id, new.representante_id)
       where id = v_visita_id;
    end if;
    new.visita_id := v_visita_id;

    -- linhas vendidas viram "linhas que trabalha"
    insert into cliente_produtos (cliente_id, produto_id)
    select distinct new.cliente_id, i.produto_id
      from pedido_itens i where i.pedido_id = new.id
    on conflict do nothing;
  end if;
  return new;
end $$ language plpgsql;

drop trigger if exists trg_pedido_concluir on pedidos;
create trigger trg_pedido_concluir
  before update on pedidos
  for each row execute function fn_pedido_concluir();
